name: Playwright Tests (Docker)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  playwright:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t playwright-tests .

      - name: Run Playwright tests (generate Allure results)
        run: |
          docker run --name playwright-container -e CI=true playwright-tests \
          sh -c "npx playwright test && ls -la allure-results"

      - name: Copy Allure results from container
        run: |
          docker cp playwright-container:/app/allure-results ./allure-results
          ls -la ./allure-results

      - name: Remove container
        run: docker rm playwright-container

      - name: Generate Allure HTML report
        run: |
          docker run --rm-v ${{ github.workspace }}:/work playwright-test \
          sh -c "cd /work && npx allure generate allure-results --clean -o allure-report"

      - name: Deploy Allure HTML report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure report