name: Playwright Tests (Docker)

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    playwright:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repositorygit
              uses: actions/checkout@v4

            - name: Build Docker image
              run: docker build -t playwright-tests .

            - name: Run tests and generate Allure report
              run: |
                docker run -e CI=true --name playwright-container playwright-tests \
                sh -c "npx playwright test && npx allure generate allure-results --clean -o allure-report"
                
            - name: Copy Allure results from container
              run: |
                docker cp playwright-container:/app/allure-report ./allure-report

            - name: Remove container
              run: |
                docker rm playwright-container

            - name: Upload Allure results
              uses: actions/upload-artifact@v4
              with:
                name: allure-results
                path: allure-results

